export const CONFIG = {
  TEMP_DIR: "./temp",
  AUTH_DIR: "./auth_info", 
  BLACKLIST_FILE: "./blacklist.json",
  MAX_RECONNECT_ATTEMPTS: 3,
  RECONNECT_DELAY: 5000,
  MIN_CLEAN_INTERVAL: 60000,
  STICKER_SIZE: 512,
  STICKER_QUALITY: 90,
  VIDEO_DURATION: 6,
  GIF_DURATION: 8,
  GIF_FPS: 15,
  VIDEO_FPS: 15,
  MAX_FILE_SIZE: 800,
  WEBP_QUALITY: 75,
  MAX_GIF_FRAMES: 50,
  TIMEOUT_MS: 60000,
  KEEPALIVE_MS: 30000,
};

export const COMMANDS = {
  STICKER: "!sticker",
  IMAGE: "!image", 
  GIF: "!gif",
  EVERYONE: "@everyone",
  BLACKLIST_ADD: "!blacklist add",
  BLACKLIST_REMOVE: "!blacklist remove", 
  BLACKLIST_LIST: "!blacklist list",
  BLACKLIST_CLEAR: "!blacklist clear",
  LUMA_STATS: "!luma stats",
  LUMA_CLEAR: "!luma clear",
  MY_NUMBER: "!meunumero"
};

export const MESSAGES = {
  INITIALIZING: "🤖 WhatsApp Sticker Bot - Conversor Completo",
  STICKER_COMMAND: "🔄 !sticker - Converte imagem/vídeo para sticker",
  IMAGE_COMMAND: "🖼️ !image - Converte sticker para imagem", 
  GIF_COMMAND: "🎬 !gif - Converte sticker animado para GIF",
  WAITING_QR: "📱 Aguarde o QR Code...",
  CONNECTING: "🔄 Iniciando conexão com WhatsApp...",
  CONNECTED: "✅ Conectado com sucesso!",
  BOT_READY: "🎯 Bot pronto para uso",
  DISCONNECTED: "❌ Conexão fechada:",
  SEND_MEDIA_STICKER: "ℹ️ Envie uma mídia com !sticker",
  REPLY_MEDIA_STICKER: "ℹ️ Responda a uma imagem/vídeo com !sticker",
  SEND_STICKER_IMAGE: "ℹ️ Envie um sticker com !image",
  REPLY_STICKER_IMAGE: "ℹ️ Responda a um sticker com !image", 
  SEND_STICKER_GIF: "ℹ️ Envie um sticker animado com !gif",
  REPLY_STICKER_GIF: "ℹ️ Responda a um sticker animado com !gif",
  STATIC_STICKER: "ℹ️ Este é um sticker estático. Use !image para converter",
  CONVERTED_IMAGE: "🖼️ Convertido!",
  EVERYONE_COMMAND: "📢 @everyone - Marca todos os integrantes do grupo",
  CONVERTED_GIF: "🎬 Convertido!",
  DOWNLOAD_ERROR: "❌ Erro ao baixar",
  CONVERSION_ERROR: "❌ Erro na conversão",
  UNSUPPORTED_FORMAT: "❌ Este sticker usa um formato que não consigo converter. Desculpe!",
  GENERAL_ERROR: "❌ Erro",
};